version: 2

build:
  os: ubuntu-22.04
  tools:
    nodejs: "20"

jobs:
  pre_build:
    steps:
      - checkout
      - run:
          name: "Setup environment"
          command: |
            curl -fsSL https://get.pnpm.io/install.sh | sh -
            export PNPM_HOME="$HOME/.local/share/pnpm"
            export PATH="$PNPM_HOME:$PATH"
            
            pnpm install
  build:
    steps:
      - run:
          name: "Build documentation"
          command: |
            export PNPM_HOME="$HOME/.local/share/pnpm"
            export PATH="$PNPM_HOME:$PATH"
            
            # build
            pnpm run docs:build
            
            mkdir -p $READTHEDOCS_OUTPUT/html
            mv -r docs/.vitepress/dist/* $READTHEDOCS_OUTPUT/html/